language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - ~/.npm
notifications:
  email: false
install:
  - npm install
  - npm install semantic-release --no-save
script:
  - npm run test
  - npm run build
  - npx semantic-release
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
